name: Nick Bunton Web Development Blog
description: Blogging About Web Development
meta_description: "Nick Bunton, Blogging about web development"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'https://buntonn@github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'web-dev-blog'

# Details for the RSS feed generator
url:            'https://buntonn@github.io'
author:         'Nick Bunton'
authorTwitter:  '@nucubedesign'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
